title: "Ring Oscillator Transient 1"
source: "./Ring_Oscillator_7stage.raw"

X:
  label: "Time (s)"
  signal_key: "raw.time"

Y:
  - label: "Voltage (V)"
    signals:
      BUS06: "v(bus06)"
      BUS07: "v(bus07)"
  - label: "Voltage (V)"
    signals:
      BUS08: "v(bus08)"
