
title: "File-Based YAML Configuration"
X:
  signal_key: "raw.time"
  label: "Time (s)"
Y:
  - label: "Selected Signals (V)"
    signals:
      Input: "v(in)"
      Output: "v(out)"
      Bias: "v(i_bias)"
plot_height: 500
